name: moodiary
description: "A Flutter app for journaling moods and daily reflections with motivational quotes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Icon set
  cupertino_icons: ^1.0.8

  # HTTP request for fetching quotes API
  http: ^1.2.1

  # Modern font styling
  google_fonts: ^6.1.0

  # Chart
  fl_chart: ^0.68.0

  # Database lokal SQLite
  sqflite: ^2.2.8+4
  path: ^1.8.3
  flutter_dotenv: ^5.1.0
  table_calendar: ^3.1.1  # ðŸ‘ˆ Tambahkan ini
  intl: ^0.19.0           # ðŸ‘ˆ Tambahkan ini (untuk format tanggal)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  # Assets (for local dummy data)
  assets:
    - .env